apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site
  namespace: argocd
spec:
  destination:
    namespace: site
    server: "https://kubernetes.default.svc"
  project: default
  source:
      repoURL: git@github.com:REDACTED/kasil-apps.git
      targetRevision: HEAD
      path: apps/site
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # automated: {}
      # selfHeal: true
