---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
  namespace: mysql
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.democratic-csi.zfs-local-dataset
    fsType: zfs
    volumeAttributes:
      node_attach_driver: zfs-local
      provisioner_driver: zfs-local-dataset
      zfs_asset_name: main/k8s/static/mysql
    volumeHandle: main/k8s/static/mysql
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-mysqlcluster-0
    namespace: mysql
