apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  destination:
    namespace: frigate
    server: "https://kubernetes.default.svc"
  project: default
  sources:

  # Repo itself
  - repoURL: 'git@github.com:REDACTED/kasil-apps.git'
    path: "apps/frigate"
    targetRevision: HEAD
    ref: values

  # Operator
  - repoURL: 'https://blakeblackshear.github.io/blakeshome-charts/'
    chart: frigate
    targetRevision: "7.0.1"
    helm:
      valueFiles:
      - $values/apps/frigate/values-frigate.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # automated: {}
      # selfHeal: true

  ignoreDifferences:
  - group: ""  # v1
    kind: PersistentVolume
    name: frigate-media
    jsonPointers:
    - /spec/claimRef/resourceVersion
    - /spec/claimRef/uid
