apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
  namespace: frigate
spec:
  storageClassName: ""
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.democratic-csi.nfs
    fsType: nfs
    volumeHandle: /mnt/camera/recording
    volumeAttributes:
      node_attach_driver: nfs
      server: storage.my-home-lab.cloud
      share: /mnt/camera/recording
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: frigate-media-pvc
    namespace: frigate
