apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: frigate
spec:
  storageClassName: ""
  volumeName: frigate-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti
