apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
  namespace: homeassistant
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.democratic-csi.nfs
    fsType: nfs
    volumeHandle: /mnt/main/k8s/static/homeassistant
    volumeAttributes:
      node_attach_driver: nfs
      server: storage.my-home-lab.cloud
      share: /mnt/main/k8s/static/homeassistant
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: homeassistant-config-pvc
    namespace: homeassistant
