apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
spec:
  storageClassName: ""
  volumeName: homeassistant-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
